[env:esp32-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; native USB (не UART-мост) — без этого Serial.println() не будет работать
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DLV_USE_TFT_ESPI=0

; на плате 16MB flash + 8MB octal PSRAM
board_build.partitions = default_16MB.csv
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

; файловая система для хранения ресурсов
board_build.filesystem = littlefs

; Библиотеки для LVGL
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    lvgl/lvgl @ ^9.2.0
    ; Если используете TFT_eSPI как драйвер дисплея
    bodmer/TFT_eSPI @ ^2.5.43
